version: '2'
services:
  web:
    build: .
    volumes:
     - /uploads:/web/public/uploads
     - $PWD:/web
    links:
      - postgres
      - memcached
  postgres:
    image: "postgres:9.6.1-alpine"
  memcached:
    image: "memcached:1.4.34-alpine"
  nginx:
    image: "nginx:1.10.2-alpine"
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf:ro
      - /root/logs/:/var/log/nginx/
    ports:
      - 80:80
    links:
      - web
